GET http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NDNlNDkwYzI1YzE5OGFlMTljYTY4ZDEiLCJpYXQiOjE2ODE4MTc4MDB9.-fBcZFpaSCY0IjjDCsH3W6NizeI9hhTdIXp_WaeMRYg
